### ISSUE TITLE
Can not access a directory containing broken symlink in WebUI

### ISSUE THREAD

**Issue by kiteMN9** [Kodecable/wsfs-core#1]
**Description**

In WebDAV/WebUI, Accessing a directory containing broken symlink (a symlink pointing to a nonexistent target) returns an HTTP 404.

**Steps to Reproduce**

1. Configure `wsfs` to serve a directory.
2. Create a broken symlink in the served directory:
```sh
$ ln -s /nonexistent/path /path/to/served/directory/broken_symlink
```
3. Access the directory through the browser.

**Observed Behavior**

The server returns HTTP 404 Not Found.

**Expected Behavior**

Accessing the directory should return the usual WebUI File List, where other files in the directory are displayed correctly. The server should try its best to provide context to the user.

**Comment by Kodecable** [comment]
Fixed in 235d654f02bad5a9aa5e8d46ee20098a25df808b.
